### ISSUE TITLE
Feature request: switch to Benny

### ISSUE THREAD

**Issue by vicb** [pckhoi/jest-bench#10]
It looks like benchmark.js is old and not very maintained any more.

benchmark.js tries to "recompile" the function and it's cuasing troubles:

```
import { benchmarkSuite } from 'jest-bench';
import { readFileSync } from 'node:fs';
import path from 'node:path';

let png;

benchmarkSuite('sample', {
  setup: () => {
    png = readFileSync(path.join(__dirname, 'fixtures', 'x529y267z10.png'));
  },

  // ...
});
```

Trying to execute this code will result in an error:

```
    ReferenceError: node_fs_1 is not defined

      at Benchmark.eval [as compiled] (eval at createCompiled (../../node_modules/benchmark/benchmark.js:1725:16), <anonymous>:4:166)
      at clock (../../node_modules/benchmark/benchmark.js:1621:50)
      at cycle (../../node_modules/benchmark/benchmark.js:2007:49)
      at Benchmark.run (../../node_modules/benchmark/benchmark.js:2114:13)
      at execute (../../node_modules/benchmark/benchmark.js:860:74)
      at Timeout.<anonymous> (../../node_modules/lodash/lodash.js:2792:43)
```

More generally if you declare any function in the scope of the file it wouldn;t work, i.e.:

```
import { benchmarkSuite } from 'jest-bench';

function init() {
 // ...
}

benchmarkSuite('sample', {
  setup: () => {
    init();    
  },

  // ...
});
```

I think [benny](https://github.com/caderek/benny) could solve this and the API could stay the same.

What do you think?

**Comment by pckhoi** [comment]
I mentioned it in the README. setup and teardown are evaled together with the function so any variable from outer scopes will be invisible.

Also looks like benny is also using benchmark.js underneath so how would it be any different?

**Comment by vicb** [comment]
> I mentioned it in the README. setup and teardown are evaled together with the function so any variable from outer scopes will be invisible.

I missed that from the README. Thank you for clarifying.

> Also looks like benny is also using benchmark.js underneath so how would it be any different?

You are absolutely right. I missed that and I thought it was a rewrite.
