### ISSUE TITLE
NPM version is not in sync with Github

### ISSUE THREAD

**Issue by jairmilanes** [pckhoi/jest-bench#13]
Somehow your NPM package is not in sync with what the code shows here in Github, the version is the same `v29.3.1` but the NPM package does not yet include the code merged in #11.

You can verify it here, seems it was not built before publishing, https://www.npmjs.com/package/jest-bench?activeTab=explore

Cheers!

**Comment by pckhoi** [comment]
Thanks for pointing that out. Perhaps I didn't run `build` before `publish`. I have just published v29.3.2 and looks like it does have the new code.

**Comment by jairmilanes** [comment]
Thank you! Cheers!
