### ISSUE TITLE
Regression/Optimization Checking

### ISSUE THREAD

**Issue by JonoPrest** [pckhoi/jest-bench#15]
Hi there,

I've really enjoyed testing out this package and considering using it for a project that's going to rely heavily on benchmarking. I'm interested if there is any plan for the reporter to report on the diff between the last result.txt saved and the current benchmark run. It would be really useful to monitor regressions and optimizations during development.

It would also be really useful for CI pipeline.

**Comment by pckhoi** [comment]
No plan for regression monitoring yet. But a poor man's implementation might be to just output the final report to a text file that you can keep in version control with Git. Would that suffice for your purpose?

**Comment by JonoPrest** [comment]
> No plan for regression monitoring yet. But a poor man's implementation might be to just output the final report to a text file that you can keep in version control with Git. Would that suffice for your purpose?

Hi @pckhoi, sorry I didn't see your reply. Thanks very much - yeah I was thinking of doing something like what you suggest.
