### ISSUE TITLE
Slow performance? 

### ISSUE THREAD

**Issue by dwjohnston** [pckhoi/jest-bench#16]
I've been playing around with what you've got. And it takes like 31 seconds to run the whole suite. 

However, each test isn't actually expensive, you can say they take a matter of microseconds. 

Where's all that time going? 

```
Benchmarks:
  error
    should throw error  0.000 μs ±  0.00 %  (0 runs sampled)
  deferred
    deferred  10.97 ms ±  0.23 %  (86 runs sampled)
  regexp
    test  0.013 μs ±  0.57 %  (96 runs sampled)
  string
    indexOf  0.001 μs ±  0.14 %  (99 runs sampled)
    match    0.025 μs ±  0.17 %  (99 runs sampled)
  string with SuiteOptions
    indexOf  0.001 μs ±  0.25 %  (10 runs sampled)
    match    0.026 μs ±  0.52 %  (14 runs sampled)
  setup teardown
    Array.indexOf    0.005 ms ±  0.43 %  (96 runs sampled)
    delete Array[i]  0.029 ms ±  3.49 %  (91 runs sampled)
    Array.unshift    0.004 ms ±  5.71 %  (57 runs sampled)
    Array.push       0.074 μs ±  0.56 %  (95 runs sampled)
  setupSuite
    Array.indexOf  0.001 ms ±  85.25 %  (91 runs sampled)

Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, 11 passed, 12 total
Snapshots:   0 total
Time:        31.115 s

```

**Comment by pckhoi** [comment]
To come up with accurate benchmarks, each test is not run just once but
hundreds perhaps thousands of time. Tests that produce more volatile
performance need more runs than tests that are more stable. You should look
at the `benchmark` package to understand more.

**Comment by dwjohnston** [comment]
@pckhoi  Where it says '(96 runs sampled)' does that mean a 'run' is actually running the function  thousands of times? 

Is it possible to configure this to reduce the number of runs/max run time. Purely for the purposes of debugging. 

Also - what I'm actually looking at this for, is I want to be doing performance monitoring on API contract tests. ie. it's plausible that responses might be in the hundreds of milliseconds. Fair to say that this wouldn't be an appropriate tool for that use case?

**Comment by pckhoi** [comment]
To performance test an entire API, have a look at k6. It might also be worth while to setup Grafana to monitor resource usage and test metrics.

Only use this tool to benchmark individual functions.

**Comment by dwjohnston** [comment]
@pckhoi  Any thoughts about the appropriateness of this for React unit tests? 

A very easy thing to do in React, is to create an application that renders the whole tree every key stroke of a form. If the tree is large enough, you can get the whole thread being blocked/getting pauses between key strokes and visual feedback. 

An RTL test, with close-to-deterministic performance metrics would help with detecting this.

**Comment by pckhoi** [comment]
This tool is more appropriate for library developers. Data or render intensive libraries that is.

For React applications, I'd say it is more fruitful to first identify the parts that are slow or the parts that you REALLY want to make fast. Use the React profiler API to find the bottlenecks and try to improve them. I've never heard of anyone trying to write benchmarks for React components. Perhaps if you're writing a complex redux selector that really need to be fast then it makes sense. React itself is already written to be very fast if you're using it correctly.

It is also not a good idea to turn all of your unit tests into benchmarks. The purpose is different.

**Comment by dwjohnston** [comment]
Just the close the loop here - the [React Profiler](https://react.dev/reference/react/Profiler) component is perfect for what I'm describing here.
