### ISSUE TITLE
Jest warning: unknown option "reporters"

### ISSUE THREAD

**Issue by RobinTail** [pckhoi/jest-bench#17]
Thank you very much for this library. Really made my day :)

I was following the instruction in Readme exactly, having Jest 29 with `jsdom` environment.
The benchmark tests run and report well.

However, there is a warning message from Jest:

```
● Validation Warning:

  Unknown option "reporters" with value ["default", "jest-bench/reporter"] was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

Is there any way to fix it?

**Comment by RobinTail** [comment]
Seems to be related to this bug of Jest 29:
https://github.com/jestjs/jest/issues/13576

**Comment by pckhoi** [comment]
I don't think there's any action possible from this end right now.
