### ISSUE TITLE
Feature request: add ability to set Benchmark options

### ISSUE THREAD

**Issue by vicb** [pckhoi/jest-bench#7]
[Benchmark](https://benchmarkjs.com/docs/#Benchmark) takes options.

It would be useful to add them as a parameter to `benchmarkSuite()`.

I could help implement this.

**Comment by pckhoi** [comment]
I see that you have added `defer` in #9. What other options/use cases that you want to support?

**Comment by vicb** [comment]
I'm most interested in configuring `minSamples` `maxTime` and `initCount`

But It would be more flexible to allow any [option](https://benchmarkjs.com/docs/#options)

I can work on an implementation if you like

**Comment by pckhoi** [comment]
I think adding support for those would be fantastic! Are you planning to add those to benchmarkSuite options? If so, feel free to open a PR.

Adding `delay` and `minTime` is probably a good idea as well. But I'm not sure about adding blanket support for all options. This package's options is obviously not a one-to-one mapping with Benchmark's.

**Comment by vicb** [comment]
I'll work on a PR with what I have in mind. Thanks for the feedback.
