### ISSUE TITLE
Feature request: disable file output

### ISSUE THREAD

**Issue by vicb** [pckhoi/jest-bench#8]
It would be nice to have an option to disable the file output of jest-bench

Thanks!

**Comment by pckhoi** [comment]
Why do you want to disable file output? Are you out of disk space?

**Comment by vicb** [comment]
I don't need the file output which is why I'd like to be able to disable it.

One problem with the current implementation is that the file in generated in the [process working directory](https://github.com/pckhoi/jest-bench/blob/main/src/reporter.ts#L38). That does not play well with a monorepo setup.

I think the file should be generated in the directory of the jest config file instead.

**Comment by pckhoi** [comment]
Fair points. I guess adding option `disableFileOutput` would do the trick for now?

**Comment by vicb** [comment]
>  I guess adding option disableFileOutput would do the trick for now?

That would be nice.

I would be great to fix the output path at the same time (to output in the same folder as where the config is).

**Comment by pckhoi** [comment]
Agreed. Feel free to open a PR. If not, I will make one whenever time allow.
